[tox]
min_version = 4.0
env_list = train, test_package, checks
skipsdist = true

[testenv]
base_python = python
set_env =
    PYTHONPATH = .
    PYTHONHASHSEED = 0

[testenv:train]
description = Train the model
deps =
    -r requirements/test_requirements.txt
commands =
    python -m regression_model.train_pipeline

[testenv:test_package]
description = Train model and run tests
deps =
    -r requirements/test_requirements.txt
commands =
    python -m regression_model.train_pipeline
    pytest -s -vv {posargs:tests}

[testenv:checks]
description = Run static analysis
deps =
    -r requirements/typing_requirements.txt
commands =
    flake8 regression_model tests
    isort regression_model tests
    mypy regression_model

[flake8]
exclude = .git,.tox,env
max-line-length = 100